[theme]
base="light"
primaryColor="#0f988b"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#31333F"
font="sans serif"

[server]
# Đã bỏ dấu / ở cuối tên miền để đảm bảo hoạt động chuẩn xác
frameAncestors = ["'self'", "https://yogaismylife.vn"]
enableCORS = false
enableXsrfProtection = false
